/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.mhealth.open.data.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2339500714367089464L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MEvent\",\"namespace\":\"org.mhealth.open.data.avro\",\"fields\":[{\"name\":\"user_id\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"measures\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"Measure\",\"fields\":[{\"name\":\"unit\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"value\",\"type\":\"float\"}]},\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MEvent> ENCODER =
      new BinaryMessageEncoder<MEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MEvent> DECODER =
      new BinaryMessageDecoder<MEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MEvent from a ByteBuffer. */
  public static MEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String user_id;
  @Deprecated public long timestamp;
  @Deprecated public java.util.Map<java.lang.String,org.mhealth.open.data.avro.Measure> measures;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MEvent() {}

  /**
   * All-args constructor.
   * @param user_id The new value for user_id
   * @param timestamp The new value for timestamp
   * @param measures The new value for measures
   */
  public MEvent(java.lang.String user_id, java.lang.Long timestamp, java.util.Map<java.lang.String,org.mhealth.open.data.avro.Measure> measures) {
    this.user_id = user_id;
    this.timestamp = timestamp;
    this.measures = measures;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return user_id;
    case 1: return timestamp;
    case 2: return measures;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: user_id = (java.lang.String)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: measures = (java.util.Map<java.lang.String,org.mhealth.open.data.avro.Measure>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.String getUserId() {
    return user_id;
  }

  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'measures' field.
   * @return The value of the 'measures' field.
   */
  public java.util.Map<java.lang.String,org.mhealth.open.data.avro.Measure> getMeasures() {
    return measures;
  }

  /**
   * Sets the value of the 'measures' field.
   * @param value the value to set.
   */
  public void setMeasures(java.util.Map<java.lang.String,org.mhealth.open.data.avro.Measure> value) {
    this.measures = value;
  }

  /**
   * Creates a new MEvent RecordBuilder.
   * @return A new MEvent RecordBuilder
   */
  public static org.mhealth.open.data.avro.MEvent.Builder newBuilder() {
    return new org.mhealth.open.data.avro.MEvent.Builder();
  }

  /**
   * Creates a new MEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MEvent RecordBuilder
   */
  public static org.mhealth.open.data.avro.MEvent.Builder newBuilder(org.mhealth.open.data.avro.MEvent.Builder other) {
    return new org.mhealth.open.data.avro.MEvent.Builder(other);
  }

  /**
   * Creates a new MEvent RecordBuilder by copying an existing MEvent instance.
   * @param other The existing instance to copy.
   * @return A new MEvent RecordBuilder
   */
  public static org.mhealth.open.data.avro.MEvent.Builder newBuilder(org.mhealth.open.data.avro.MEvent other) {
    return new org.mhealth.open.data.avro.MEvent.Builder(other);
  }

  /**
   * RecordBuilder for MEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MEvent>
    implements org.apache.avro.data.RecordBuilder<MEvent> {

    private java.lang.String user_id;
    private long timestamp;
    private java.util.Map<java.lang.String,org.mhealth.open.data.avro.Measure> measures;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.mhealth.open.data.avro.MEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.measures)) {
        this.measures = data().deepCopy(fields()[2].schema(), other.measures);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(org.mhealth.open.data.avro.MEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.measures)) {
        this.measures = data().deepCopy(fields()[2].schema(), other.measures);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return user_id;
    }

    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public org.mhealth.open.data.avro.MEvent.Builder setUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.user_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public org.mhealth.open.data.avro.MEvent.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public org.mhealth.open.data.avro.MEvent.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public org.mhealth.open.data.avro.MEvent.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'measures' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,org.mhealth.open.data.avro.Measure> getMeasures() {
      return measures;
    }

    /**
      * Sets the value of the 'measures' field.
      * @param value The value of 'measures'.
      * @return This builder.
      */
    public org.mhealth.open.data.avro.MEvent.Builder setMeasures(java.util.Map<java.lang.String,org.mhealth.open.data.avro.Measure> value) {
      validate(fields()[2], value);
      this.measures = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'measures' field has been set.
      * @return True if the 'measures' field has been set, false otherwise.
      */
    public boolean hasMeasures() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'measures' field.
      * @return This builder.
      */
    public org.mhealth.open.data.avro.MEvent.Builder clearMeasures() {
      measures = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MEvent build() {
      try {
        MEvent record = new MEvent();
        record.user_id = fieldSetFlags()[0] ? this.user_id : (java.lang.String) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.measures = fieldSetFlags()[2] ? this.measures : (java.util.Map<java.lang.String,org.mhealth.open.data.avro.Measure>) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<MEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MEvent>
    READER$ = (org.apache.avro.io.DatumReader<MEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
